### ISSUE TITLE
Not compatiable

### ISSUE THREAD

**Issue by bilpor** [kekekeks/NObservable#1]
Hi, This looks exactly what I need for a Blazor issue I have. However, after installing the package and trying to add a reference in my Startup.cs file I receive an error that I need to reference Microsoft.AspNetCore.Blazor.Browser 0.5.1 I'm using 0.7.0 and don't really want 2 versions of Blazor.Browser installed. could you update the package ot run with 0.7.0.

Thanks

**Comment by kekekeks** [comment]
I'm currently getting InvalidProgramException with updated Blazor. Will investigate next week.

**Comment by kekekeks** [comment]
It was actually a bug with wrong method call being emitted. 

Uploaded 0.1.1 that targets Blazor 0.7.0 - https://www.nuget.org/packages/NObservable.Blazor/0.1.1
